### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Instagram-Post_Layout#1]
# Revisión - Aprobado
- [x] Estilo de código y limpieza
# Feedback
- ¡Muy buen trabajo. Felicidades @arkngel212  !
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- En la etiqueta de apertura < button > en el bloque .else-logo, parece que la etiqueta < i > está cerrada con una etiqueta < /i > que no está abierta. Puedes eliminar esta etiqueta de cierre o corregirla si era parte de algo que querías incluir.
- Recuerda que el nombre de los repositorios del curso deberían ser algo así como TuNombre-Post-de-instagram. (Es importante esto para luego poder identificar de forma rápida tus proyectos de entre todos los proyectos de los alumnos de 4geeksacademy).

**Comment by pordunazarzosa** [comment]
Gracais @EduardoHernandezGuzman por el feedback

**Comment by EduardoHernandezGuzman** [comment]
¡Buen primer proyecto!
